sudo: false
language: node_js
node_js:
  - "7"
  - "8"
  - "9"
before_install:
  - sudo apt-get install texlive-full
install:
  - npm run build
script:
  - npm test
cache:
  directories:
    - "app/client/node_modules"
    - "app/server/node_modules"
