name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  check-format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run format:check
      - run: npm run lint
